<a href="https://colab.research.google.com/github/shriju/pytorch/blob/main/tensors_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: ", {torch.cuda.get_device_name(0)})
else:
  print("GPU is not available, only CPU")

GPU is not available, only CPU


### creating a tensor

In [4]:
# using empty
a= torch.empty(2,3)


In [5]:
# check type
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand, values between 0-1
torch.rand(2,3)

tensor([[0.0464, 0.0763, 0.8621],
        [0.6633, 0.5761, 0.6884]])

In [8]:
# manual_seed, for reproducebility
torch.manual_seed(100)
torch.rand(2,3)



tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
# manual_seed, for reproducebility, checking if it produces the same code
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
# using tensor
torch.tensor([[2,3,4], [5,6,7]])

tensor([[2, 3, 4],
        [5, 6, 7]])

In [11]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### Tensor Shapes

In [12]:
x= torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
x.shape

torch.Size([2, 3])

In [14]:
# copying the shape of a tensor
torch.empty_like(x)

tensor([[133954197798272, 133954197798272,    197568495720],
        [   468151435365,    498216206448, 133951440027769]])

In [15]:
# same shape but with zeros
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
# same shape but ones
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [18]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

### Tensor Data Types

In [19]:
# find data type
x.dtype

torch.int64

In [20]:
# assign data type
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [21]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Mathematical Operations

#### Scaler Operationa

In [30]:
# addition
x+2

# Subtraction
x-2

# Multiplication
x*3

# Division

x/3

# int Division
(x*100)//3

# mod
((x*100)//3)%2

# power
x**2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

### 2. Element Wise Operation

In [31]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])
tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])


In [37]:
# add
a+b

# subtract
a-b

# multiply
a*b

# division
a/b

# power
a**b

# mod
a % b

tensor([[0.0401, 0.1829, 0.0615],
        [0.0776, 0.4411, 0.7565]])

In [38]:
c = torch.tensor([1, -2, 3, -4])

In [39]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [40]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [41]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [42]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [43]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [44]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [46]:
# clamp minimum number will be 2 and max number will be 3 in this case
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### Reduction Operation

In [48]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[7., 0., 0.],
        [9., 5., 7.]])

In [49]:
# sum
torch.sum(e)

tensor(28.)

In [50]:
# sum along columns
torch.sum(e, dim=0)

tensor([16.,  5.,  7.])

In [51]:
# sum along rows
torch.sum(e, dim=1)

tensor([ 7., 21.])

In [52]:
# mean
torch.mean(e)

tensor(4.6667)

In [53]:
# mean along cols
torch.mean(e, dim=0)

tensor([8.0000, 2.5000, 3.5000])

In [54]:
# mean along rows
torch.mean(e, dim=1)

tensor([2.3333, 7.0000])

In [55]:
# median
torch.median(e)

tensor(5.)

In [56]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [57]:
# product
torch.prod(e)

tensor(0.)

In [58]:
# standard deviation
torch.std(e)

tensor(3.8297)

In [59]:
# variance
torch.var(e)

tensor(14.6667)

In [62]:
# argmax, tells the position of the max number
torch.argmax(e)

tensor(3)

In [61]:
# argmin
torch.argmin(e)

tensor(1)

### matrix operations

In [63]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[3, 9, 4],
        [0, 5, 7]])
tensor([[5, 9],
        [9, 7],
        [5, 9]])


In [64]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[116, 126],
        [ 80,  98]])

In [65]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [67]:
# transpose
print(f)
torch.transpose(f, 0, 1)

tensor([[3, 9, 4],
        [0, 5, 7]])


tensor([[3, 0],
        [9, 5],
        [4, 7]])

In [68]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[8., 9., 7.],
        [9., 2., 6.],
        [7., 7., 8.]])

In [69]:
# determinant
torch.det(h)

tensor(-135.0000)

In [70]:
# inverse
torch.inverse(h)

tensor([[ 0.1926,  0.1704, -0.2963],
        [ 0.2222, -0.1111, -0.1111],
        [-0.3630, -0.0519,  0.4815]])

In [6]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[5, 1, 1],
        [4, 9, 7]])
tensor([[0, 1, 4],
        [6, 3, 6]])


### Comparisons Operations

In [10]:
# greater than
i > j

# less than
i < j

# equal to
i == j

# not equal to
i != j

tensor([[ True, False,  True],
        [ True,  True,  True]])

### Special Functions

In [11]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[1., 1., 3.],
        [5., 6., 6.]])

In [12]:
# log
torch.log(k)

tensor([[0.0000, 0.0000, 1.0986],
        [1.6094, 1.7918, 1.7918]])

In [13]:
# exp
torch.exp(k)

tensor([[  2.7183,   2.7183,  20.0855],
        [148.4132, 403.4288, 403.4288]])

In [14]:
# sqrt
torch.sqrt(k)

tensor([[1.0000, 1.0000, 1.7321],
        [2.2361, 2.4495, 2.4495]])

In [15]:
# sigmoid
torch.sigmoid(k)

tensor([[0.7311, 0.7311, 0.9526],
        [0.9933, 0.9975, 0.9975]])

In [16]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.0180, 0.0067, 0.0474],
        [0.9820, 0.9933, 0.9526]])

In [17]:
# relu
torch.relu(k)

tensor([[1., 1., 3.],
        [5., 6., 6.]])

### Inplace Operations

In [18]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6221, 0.3146, 0.4642],
        [0.1055, 0.3379, 0.5726]])
tensor([[0.4175, 0.4240, 0.7867],
        [0.6183, 0.9541, 0.8734]])


In [19]:
m.add_(n)

tensor([[1.0396, 0.7386, 1.2508],
        [0.7238, 1.2921, 1.4460]])

In [20]:
m

tensor([[1.0396, 0.7386, 1.2508],
        [0.7238, 1.2921, 1.4460]])

In [21]:
n

tensor([[0.4175, 0.4240, 0.7867],
        [0.6183, 0.9541, 0.8734]])

In [22]:
torch.relu(m)

tensor([[1.0396, 0.7386, 1.2508],
        [0.7238, 1.2921, 1.4460]])

In [23]:
m.relu_() # changes permanently in m

tensor([[1.0396, 0.7386, 1.2508],
        [0.7238, 1.2921, 1.4460]])

In [24]:
m

tensor([[1.0396, 0.7386, 1.2508],
        [0.7238, 1.2921, 1.4460]])

### Copying a tensor

In [25]:
a = torch.rand(2,3)
a

tensor([[0.6920, 0.7540, 0.4071],
        [0.2826, 0.9444, 0.4351]])

In [26]:
b = a

In [27]:
b

tensor([[0.6920, 0.7540, 0.4071],
        [0.2826, 0.9444, 0.4351]])

In [28]:
a[0][0]=0

In [29]:
a

tensor([[0.0000, 0.7540, 0.4071],
        [0.2826, 0.9444, 0.4351]])

In [30]:
b

tensor([[0.0000, 0.7540, 0.4071],
        [0.2826, 0.9444, 0.4351]])

In [31]:
id(a)

134261990358576

In [32]:
id(b)

134261990358576

In [33]:
b = a.clone()

In [34]:
a

tensor([[0.0000, 0.7540, 0.4071],
        [0.2826, 0.9444, 0.4351]])

In [35]:
b

tensor([[0.0000, 0.7540, 0.4071],
        [0.2826, 0.9444, 0.4351]])

In [36]:
a[0][0] = 10

In [37]:
a

tensor([[10.0000,  0.7540,  0.4071],
        [ 0.2826,  0.9444,  0.4351]])

In [38]:
b

tensor([[0.0000, 0.7540, 0.4071],
        [0.2826, 0.9444, 0.4351]])

In [39]:
id(a)

134261990358576

In [40]:
id(b)

134261753734512

## Tensors operations on GPU


In [3]:
torch.cuda.is_available()

False

In [ ]:
device=torch.device('cuda')


In [ ]:
# creating a new tensor in GPU
torch.rand((2,3), device=device)

In [ ]:
# moving an existing tensor to GPU
a=torch.rand(2,3)
a

In [ ]:
b = a.to(device)

In [ ]:
b+5

## Reshaping Tensors

In [ ]:
a=torch.ones(4,4)
a

In [ ]:
# reshape
a.reshape(2,2,2,2)

In [ ]:
# flatten
a.flatten()

In [ ]:
# permute
b=torch.rand(2,3,4)
b

In [ ]:
b.permute(2,0,1).shape

In [ ]:
# unsqueeze
c= torch.rand(226,226,3)
c.unsqueeze(0).shape

In [ ]:
# squeeze
d=torch.rand(1,20)
d.squeeze(0).shape

## Numpy and Pytorch

In [1]:
import numpy as np

In [ ]:
a=torch.tensor([1,2,3])
a

In [ ]:
b=a.numpy()
b

In [ ]:
c=np.array([1,2,3])
c

In [ ]:
torch.from_numpy(c)